exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo

study:
  direction: maximize
  storage: "sqlite:///exp_db/retab_DeepIsolationForest.sqlite3"
  n_trials: 1000

data_parameters:
  serialize: False
  batch_size: 1000

model_parameters:
  bias: False
  lr: 0.001 # it is for consistency, unused in this model (https://deepod.readthedocs.io/en/latest/generated/deepod.models.DeepIsolationForest.html#deepod.models.DeepIsolationForest)
  act: ReLU
  max_samples: 256

hyperparameters:
  data_parameters:
    scaling_type:
      type: categorical
      grid: [standard, minmax]
    cat_encoding:
      type: categorical
      grid: [int, onehot]
  
  model_parameters:
    rep_dim:
      type: categorical
      grid: [32, 128, 256]
    hidden_dims:
      type: categorical
      grid: ["100,50", "256,128", "512,256"]
    n_ensemble:
      type: categorical
      grid: [50, 200]
    n_estimators:
      type: categorical
      grid: [6, 10]
