exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo

study:
  direction: maximize
  storage: "sqlite:///exp_db/retab_DisentAD.sqlite3"
  n_trials: 1000

data_parameters:
  serialize: False
  batch_size: 512

model_parameters:
  patch_size: 1
  overlap: 0
  qkv_bias: True
  epochs: 200
  n_attr: 18
  num_heads: 2

hyperparameters:
  data_parameters:
    scaling_type: 
      type: categorical
      grid: [standard, minmax]
    cat_encoding:
      type: categorical
      grid: [int, onehot]
  model_parameters:
    learning_rate:
      type: categorical
      grid: [0.0001, 0.00001]
    hidden_dim:
      type: categorical
      grid: [128, 256]