exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo

study:
  direction: maximize
  storage: "sqlite:///exp_db/retab_DRL.sqlite3"
  n_trials: 1000

data_parameters:
  serialize: False
  batch_size: 512

model_parameters:
  epochs: 200
  sche_gamma: 0.98
  en_nlayers: 3
  de_nlayers: 3
  hidden_dim: 128
  diversity: True
  plearn: False
  input_info: True
  input_info_ratio: 0.1
  cl: True
  cl_ratio: 0.06
  basis_vector_num: 5

hyperparameters:
  data_parameters:
    scaling_type: 
      type: categorical
      grid: [standard, minmax]
    cat_encoding:
      type: categorical
      grid: [int, onehot]
  model_parameters:
    learning_rate:
      type: categorical
      grid: [0.005, 0.001, 0.0005, 0.0001]
    input_info_ratio:
      type: categorical
      grid: [0.05, 0.1, 0.15]
    cl_ratio:
      type: categorical
      grid: [0.03, 0.06, 0.09]