exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo

study:
  direction: maximize
  storage: "sqlite:///exp_db/retab_MCM.sqlite3"
  n_trials: 1000

data_parameters:
  serialize: False
  batch_size: 512

model_parameters:
  en_nlayers: 3
  de_nlayers: 3
  hidden_dim: 256
  z_dim: 128
  mask_nlayers: 3
  sche_gamma: 0.98
  epochs: 200

# for hyperparameters, search space is covering:
# https://github.com/JXYin24/MCM/issues/5
hyperparameters:
  data_parameters:
    scaling_type: 
      type: categorical
      grid: [standard, minmax]
    cat_encoding:
      type: categorical
      grid: [int, onehot]
  model_parameters:
    learning_rate:
      type: categorical
      grid: [0.005, 0.001, 0.0005, 0.0001]
    mask_num:
      type: categorical
      grid: [10, 15]
    lambda: 
      type: categorical
      grid: [1, 5, 10]
