exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo

study:
  direction: maximize
  storage: "sqlite:///exp_db/retab_KNN.sqlite3"
  n_trials: 1000

data_parameters:
  serialize: False
  batch_size: 64

model_parameters:
  algorithm: auto
  leaf_size: 30
  metric: minkowski
  p: 2
  method: largest

hyperparameters:
  data_parameters:
    scaling_type:
      type: categorical
      grid: [standard, minmax]
    cat_encoding:
      type: categorical
      grid: [int, onehot]
  
  model_parameters:
    n_neighbors:
      type: categorical
      grid: [10, 20, 30, 50]

    contamination:
      type: categorical
      grid: [0.01, 0.05, 0.1]