exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo

study:
  direction: maximize
  storage: "sqlite:///exp_db/retab_PCA.sqlite3"
  n_trials: 1000

data_parameters:
  serialize: False
  batch_size: 64
  scaling_type: standard
  cat_encoding: onehot

model_parameters:
  random_state: 42
  standardization: True
  svd_solver: auto
  weighted: True
  n_selected_components: null

hyperparameters:
  model_parameters:
    n_components:
      type: categorical
      grid: [null, 2, 3, 5, 10, 15, 20, 25, 30]
      
    contamination:
      type: categorical
      grid: [0.1, 0.2, 0.3]
    
    whiten:
      type: categorical
      grid: [true, false]